# Application Name
spring.application.name=collection-system

# Server Port
server.port=8081

# MongoDB 설정
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/realtime_sujeong}
spring.data.mongodb.database=${MONGODB_DATABASE:realtime_sujeong}

# Logging
logging.level.javacafe.realtime_sujeong=INFO
logging.level.org.springframework.data.mongodb=DEBUG