# Spring Application
spring.application.name=cleaning-system

# Active Profile
spring.profiles.active=dev

# Server Port
server.port=8082

# Logging
logging.level.root=INFO
logging.level.javacafe.realtime_sujeong=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
