spring:
  application:
    name: realtime-sujeong-collector
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432

debug: true

# Kafka 토픽 설정
kafka:
  topics:
    raw-data: raw-data-topic
    news-data: news-data-topic
    social-data: social-data-topic
    wiki-data: wiki-data-topic